export const CROPS = [
  "Wheat",
  "Rice",
  "Maize",
  "Barley",
  "Oats",
  "Sorghum (Jowar)",
  "Pearl Millet (Bajra)",
  "Finger Millet (Ragi)",
  "Foxtail Millet",
  "Barnyard Millet",
  "Kodo Millet",
  "Little Millet",
  "Chickpea (Gram)",
  "Pigeon Pea (Arhar)",
  "Green Gram (Moong)",
  "Black Gram (Urad)",
  "Lentil (Masoor)",
  "Field Pea",
  "Kidney Bean (Rajma)",
  "Cowpea",
  "Groundnut",
  "Mustard",
  "Soybean",
  "Sunflower",
  "Sesame",
  "Linseed",
  "Safflower",
  "Castor",
  "Cotton",
  "Sugarcane",
  "Tea",
  "Coffee",
  "Jute",
  "Tobacco",
  "Coconut",
  "Cashew",
  "Rubber",
  "Potato",
  "Onion",
  "Tomato",
  "Brinjal (Eggplant)",
  "Okra (Bhindi)",
  "Cauliflower",
  "Cabbage",
  "Peas (Green)",
  "Carrot",
  "Radish",
  "Spinach",
  "Chilli",
  "Garlic",
  "Ginger",
  "Turmeric",
  "Coriander",
  "Cumin",
  "Fenugreek",
  "Banana",
  "Mango",
  "Grapes",
  "Apple",
  "Guava",
  "Papaya",
  "Pomegranate",
  "Pineapple",
  "Litchi",
  "Orange",
  "Lime",
  "Watermelon",
  "Muskmelon",
  "Sapota (Chikoo)",
  "Arecanut",
  "Black Pepper",
  "Cardamom",
] as const;
